[package]
name = "rparser"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.86"
hex = "0.4.3"
nom = "7.1.3"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.116"
winnow = "0.6.18"
clap = { version = "4.5.16", features = ["derive"] }
num = { version = "0.4.3", features = ["num-bigint"] }

[[bin]]
name = "nom_app"
path = "src/nom_app.rs"

[[bin]]
name = "winnow_app"
path = "src/winnow_app.rs"

[[bin]]
name = "inclusion"
path = "src/inclusion.rs"

[[bin]]
name = "mqtt"
path = "src/mqtt.rs"
